### ISSUE TITLE
求教，用Cap替代Volo.Abp.EventBus.RabbitMQ ，有哪些优势

### ISSUE THREAD

**Issue by zhangzw218** [EasyAbp/Abp.EventBus.CAP#29]
大概可以知道，Cap会通过写数据库，做到事物一致性。
但还是想知道，有没有详细的对比，我用原生的，和用CAP的，在不同情况会有哪些区别

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/Abp.EventBus.CAP#how-do-we-integrate-cap

**Comment by zhangzw218** [comment]
额，其实我想看到的是类似：
https://github.com/EasyAbp/Abp.EventBus.Boxes.Dtm#differences-from-the-abps-default-event-boxes
这样的。
我还是说说我的问题吧，我从ABP4开始用EasyAbp，升级到Abp5之后，发现事件的发布可以在UOW内同一事物完成。
这时候就想，我是否依然需要继续使用Cap。
一时没想通，就想来官网找找对比。
