### ISSUE TITLE
CAP应该作为一个独立的EventBus而不是集成到ABP当前的EventBus下

### ISSUE THREAD

**Issue by cocosip** [EasyAbp/Abp.EventBus.CAP#3]
CAP应该作为一个独立的总线,与ABP自带的LocalEventBus, DistributedEventBus 作为并列的第三个总线来引入。
1.CAP提供的API与ABP的相差太大,即使集成到了一起,许多功能也无法全部满足。
2.使用CAP总线更多的是为了解决分布式的事物，如果仅仅是为了跟ABP现有的总线集成到一起, 许多CAP的独有的特性就没办法实现，如 多个分组订阅，动态Topic订阅等等，那么就失去了使用CAP的初衷
希望通过ABP的简单包裹，让CAP初始化更简单一些，还有CAP初始化时使用的EFContext与ABP的UnitOfWork模式可能会有一些冲突，我觉得在这些方面做一些适配与改进会更好一点。
感谢作者!

**Comment by geffzhang** [comment]
这个项目的目的就是把CAP 作为ABP的一个EventBus实现，设计就是这样的。同时把CAP 和 ABP的 EF Core和 Dapper 模块集成。
